name: make

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # The Steam Runtime platform (sniper) uses Python 3.9
          python-version: "3.9"
      - name: Install dependencies
        run: |
          sudo apt-get install podman
      - name: Initialize submodules
        run: |
          git submodule update --init --recursive
      - name: Build protonfixes in Steam Runtime
        run: |
          podman run --rm -v $(pwd):/workspace -w /workspace registry.gitlab.steamos.cloud/steamrt/sniper/sdk /bin/sh -c "make install"
